version: "3.7"
services:
  app:
    container_name: carteira_digital
    build: .
    ports:
      - 3000:3000
    environment:
      - "APP_PORT=3000"
      - "AUTHORIZATED_URL=http://run.mocky.io/v3/5794d450-d2e2-4412-8131-73d0293ac1cc"
      - "SEND_SMS_URL=https://run.mocky.io/v3/54dc2cf1-3add-45b5-b5a9-6bf7e7f1f4a6"
      - "SECRET_JWT=jg39845ytwuign8-4923yhgj-w9eirg03458hyt-9724rtgn0w98"